name: 1.4$(Rev:.r)

trigger:
- main

pr:
- main

stages:
- stage: build
  displayName: Build and Test
  
  jobs:
  - template: templates/build-job.yml
    parameters:
      isBeta: ${{ eq(variables['Build.Reason'], 'PullRequest') }}
  
- stage: publish
  displayName: Publish
  dependsOn: build
  jobs:
  - template: templates/deploy-job.yml
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      parameters:
        env: marketplace
        envName: Marketplace